//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursInfo
    {
        public KursInfo()
        {
            this.KursDetail = new HashSet<KursDetail>();
        }
    
        public int KursID { get; set; }
        public string KursName { get; set; }
    
        public virtual ICollection<KursDetail> KursDetail { get; set; }
    }
}
