//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursDetail
    {
        public int KursDetailID { get; set; }
        public string KursDate { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> KursID { get; set; }
    
        public virtual KursInfo KursInfo { get; set; }
    }
}
