//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursSayac.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class KursInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KursInfo()
        {
            this.KursDetail = new HashSet<KursDetail>();
        }
    
        public int KursID { get; set; }
        [DisplayName("Kurs Tarihi")]
        public string KursName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KursDetail> KursDetail { get; set; }
    }
}
