//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursSayac.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KursDetail
    {
        public int KursDetailID { get; set; }

        [DisplayName("Kurs Tarihi")]
        public string KursDate { get; set; }
        [DisplayName("Kiþi Sayýsý")]
        public Nullable<int> Person { get; set; }
        public Nullable<int> KursID { get; set; }
    
        public virtual KursInfo KursInfo { get; set; }
    }
}
